//
//Messages related to graph frames as used to represent results form the labeled property graph model.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.0
// source: org/polypheny/prism/graph_frame.proto

package prism

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//The GraphFrame message is a placeholder intended to represent graph frames as part of the labeled property graph model.
//As of now, the graph model is not fully implemented, making this message void of fields.
//It acts as a provision for future developments where fields related to the graph model will be added.
//Currently, this message does not contain any fields. It is reserved for future use when the graph model is more completely realized.
type GraphFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GraphFrame) Reset() {
	*x = GraphFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_graph_frame_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GraphFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphFrame) ProtoMessage() {}

func (x *GraphFrame) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_graph_frame_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphFrame.ProtoReflect.Descriptor instead.
func (*GraphFrame) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_graph_frame_proto_rawDescGZIP(), []int{0}
}

var File_org_polypheny_prism_graph_frame_proto protoreflect.FileDescriptor

var file_org_polypheny_prism_graph_frame_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c,
	0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x22, 0x0c, 0x0a, 0x0a,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x42, 0x56, 0x0a, 0x13, 0x6f, 0x72,
	0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x42, 0x10, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x19, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70,
	0x68, 0x65, 0x6e, 0x79, 0x2f, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x3b, 0x70, 0x72, 0x69, 0x73, 0x6d,
	0xaa, 0x02, 0x0f, 0x50, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x50, 0x72, 0x69,
	0x73, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_polypheny_prism_graph_frame_proto_rawDescOnce sync.Once
	file_org_polypheny_prism_graph_frame_proto_rawDescData = file_org_polypheny_prism_graph_frame_proto_rawDesc
)

func file_org_polypheny_prism_graph_frame_proto_rawDescGZIP() []byte {
	file_org_polypheny_prism_graph_frame_proto_rawDescOnce.Do(func() {
		file_org_polypheny_prism_graph_frame_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_polypheny_prism_graph_frame_proto_rawDescData)
	})
	return file_org_polypheny_prism_graph_frame_proto_rawDescData
}

var file_org_polypheny_prism_graph_frame_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_org_polypheny_prism_graph_frame_proto_goTypes = []interface{}{
	(*GraphFrame)(nil), // 0: org.polypheny.prism.GraphFrame
}
var file_org_polypheny_prism_graph_frame_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_polypheny_prism_graph_frame_proto_init() }
func file_org_polypheny_prism_graph_frame_proto_init() {
	if File_org_polypheny_prism_graph_frame_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_org_polypheny_prism_graph_frame_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GraphFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_polypheny_prism_graph_frame_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_polypheny_prism_graph_frame_proto_goTypes,
		DependencyIndexes: file_org_polypheny_prism_graph_frame_proto_depIdxs,
		MessageInfos:      file_org_polypheny_prism_graph_frame_proto_msgTypes,
	}.Build()
	File_org_polypheny_prism_graph_frame_proto = out.File
	file_org_polypheny_prism_graph_frame_proto_rawDesc = nil
	file_org_polypheny_prism_graph_frame_proto_goTypes = nil
	file_org_polypheny_prism_graph_frame_proto_depIdxs = nil
}
