// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.0
// source: org/polypheny/prism/value.proto

package prism

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specifies the type of a proto value. This enum contains a value for each datatype supported by the DBMS.
type ProtoPolyType int32

const (
	// Default unspecified type.
	ProtoPolyType_UNSPECIFIED ProtoPolyType = 0
	// Boolean type, true or false.
	ProtoPolyType_BOOLEAN ProtoPolyType = 1
	// 8-bit integer.
	ProtoPolyType_TINYINT ProtoPolyType = 2
	// 16-bit integer.
	ProtoPolyType_SMALLINT ProtoPolyType = 3
	// 32-bit integer.
	ProtoPolyType_INTEGER ProtoPolyType = 4
	// 64-bit integer.
	ProtoPolyType_BIGINT ProtoPolyType = 5
	// Arbitrary precision number.
	ProtoPolyType_DECIMAL ProtoPolyType = 6
	// Single precision floating point.
	ProtoPolyType_REAL ProtoPolyType = 7
	// Alias for REAL.
	ProtoPolyType_FLOAT ProtoPolyType = 8
	// Double precision floating point.
	ProtoPolyType_DOUBLE ProtoPolyType = 9
	//
	//Date value representing a specific day independent of time.
	//Specified in days since epoch till the start of the specified day.
	ProtoPolyType_DATE ProtoPolyType = 10
	// Time value without timezone in milliseconds since midnight.
	ProtoPolyType_TIME ProtoPolyType = 11
	// Timestamp without timezone. Specified as milliseconds since epoch.
	ProtoPolyType_TIMESTAMP ProtoPolyType = 13
	// Interval
	ProtoPolyType_INTERVAL ProtoPolyType = 15
	// Fixed length character string.
	ProtoPolyType_CHAR ProtoPolyType = 28
	// Variable length character string.
	ProtoPolyType_VARCHAR ProtoPolyType = 29
	// Text data type.
	ProtoPolyType_TEXT ProtoPolyType = 58
	// Binary data as byte string.
	ProtoPolyType_BINARY ProtoPolyType = 30
	// Variable length binary data as byte string.
	ProtoPolyType_VARBINARY ProtoPolyType = 31
	// Null type.
	ProtoPolyType_NULL ProtoPolyType = 32
	// Array type containing elements of one of the ProtoPolyTypes.
	ProtoPolyType_ARRAY ProtoPolyType = 33
	// Map type storing key value pairs. Key and value can be arbitrary values of one of the ProtoPolyTypes.
	ProtoPolyType_MAP ProtoPolyType = 34
	// Document type similar to a map but used in the document model to represent documents returned as a result.
	ProtoPolyType_DOCUMENT ProtoPolyType = 35
	// Graph type. Returned by a query in the graph data model.
	ProtoPolyType_GRAPH ProtoPolyType = 36
	// Graph node type. Used inside the graph type to represent a graphs nodes.
	ProtoPolyType_NODE ProtoPolyType = 37
	// Graph edge type. Used inside the graph type to represent a graphs edges.
	ProtoPolyType_EDGE ProtoPolyType = 38
	// Graph path type. Used in results of the graph data model to return a the result of graph queries returning a path.
	ProtoPolyType_PATH ProtoPolyType = 39
	// Image data type. Subtype of the file type. Same as binary but containing image data.
	ProtoPolyType_IMAGE ProtoPolyType = 40
	// Video data type. Subtype of the file type. Same as binary but containing video data.
	ProtoPolyType_VIDEO ProtoPolyType = 41
	// Audio data type. Subtype of the file type. Same as binary but containing audio data.
	ProtoPolyType_AUDIO ProtoPolyType = 42
	// File data type. Same as binary but containing the data of an arbitrary file.
	ProtoPolyType_FILE ProtoPolyType = 43
	// Distinct type (a named scalar type). Not supported yet!
	ProtoPolyType_DISTINCT ProtoPolyType = 44
	// Structured type. Contains an arbitrary set of other ProtoValues of any of the ProtoValueTypes. Not supported yet!
	ProtoPolyType_STRUCTURED ProtoPolyType = 45
	// Row type.
	ProtoPolyType_ROW ProtoPolyType = 46
	// Other types not specifically listed.
	ProtoPolyType_OTHER ProtoPolyType = 47
	// Cursor type.
	ProtoPolyType_CURSOR ProtoPolyType = 48
	// Column list type.
	ProtoPolyType_COLUMN_LIST ProtoPolyType = 49
	// Dynamic star type (used for dynamic column projection).
	ProtoPolyType_DYNAMIC_STAR ProtoPolyType = 50
	// Geometric data type.
	ProtoPolyType_GEOMETRY ProtoPolyType = 51
	// Symbol type.
	ProtoPolyType_SYMBOL ProtoPolyType = 52
	// JSON data type.
	ProtoPolyType_JSON ProtoPolyType = 53
	// Multiset type.
	ProtoPolyType_MULTISET ProtoPolyType = 54
	// Any type (a type that can hold any value).
	ProtoPolyType_ANY ProtoPolyType = 55
	// User-defined type.
	ProtoPolyType_USER_DEFINED_TYPE ProtoPolyType = 56
	// Row identifier type.
	ProtoPolyType_ROW_ID ProtoPolyType = 57
)

// Enum value maps for ProtoPolyType.
var (
	ProtoPolyType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "BOOLEAN",
		2:  "TINYINT",
		3:  "SMALLINT",
		4:  "INTEGER",
		5:  "BIGINT",
		6:  "DECIMAL",
		7:  "REAL",
		8:  "FLOAT",
		9:  "DOUBLE",
		10: "DATE",
		11: "TIME",
		13: "TIMESTAMP",
		15: "INTERVAL",
		28: "CHAR",
		29: "VARCHAR",
		58: "TEXT",
		30: "BINARY",
		31: "VARBINARY",
		32: "NULL",
		33: "ARRAY",
		34: "MAP",
		35: "DOCUMENT",
		36: "GRAPH",
		37: "NODE",
		38: "EDGE",
		39: "PATH",
		40: "IMAGE",
		41: "VIDEO",
		42: "AUDIO",
		43: "FILE",
		44: "DISTINCT",
		45: "STRUCTURED",
		46: "ROW",
		47: "OTHER",
		48: "CURSOR",
		49: "COLUMN_LIST",
		50: "DYNAMIC_STAR",
		51: "GEOMETRY",
		52: "SYMBOL",
		53: "JSON",
		54: "MULTISET",
		55: "ANY",
		56: "USER_DEFINED_TYPE",
		57: "ROW_ID",
	}
	ProtoPolyType_value = map[string]int32{
		"UNSPECIFIED":       0,
		"BOOLEAN":           1,
		"TINYINT":           2,
		"SMALLINT":          3,
		"INTEGER":           4,
		"BIGINT":            5,
		"DECIMAL":           6,
		"REAL":              7,
		"FLOAT":             8,
		"DOUBLE":            9,
		"DATE":              10,
		"TIME":              11,
		"TIMESTAMP":         13,
		"INTERVAL":          15,
		"CHAR":              28,
		"VARCHAR":           29,
		"TEXT":              58,
		"BINARY":            30,
		"VARBINARY":         31,
		"NULL":              32,
		"ARRAY":             33,
		"MAP":               34,
		"DOCUMENT":          35,
		"GRAPH":             36,
		"NODE":              37,
		"EDGE":              38,
		"PATH":              39,
		"IMAGE":             40,
		"VIDEO":             41,
		"AUDIO":             42,
		"FILE":              43,
		"DISTINCT":          44,
		"STRUCTURED":        45,
		"ROW":               46,
		"OTHER":             47,
		"CURSOR":            48,
		"COLUMN_LIST":       49,
		"DYNAMIC_STAR":      50,
		"GEOMETRY":          51,
		"SYMBOL":            52,
		"JSON":              53,
		"MULTISET":          54,
		"ANY":               55,
		"USER_DEFINED_TYPE": 56,
		"ROW_ID":            57,
	}
)

func (x ProtoPolyType) Enum() *ProtoPolyType {
	p := new(ProtoPolyType)
	*p = x
	return p
}

func (x ProtoPolyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoPolyType) Descriptor() protoreflect.EnumDescriptor {
	return file_org_polypheny_prism_value_proto_enumTypes[0].Descriptor()
}

func (ProtoPolyType) Type() protoreflect.EnumType {
	return &file_org_polypheny_prism_value_proto_enumTypes[0]
}

func (x ProtoPolyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoPolyType.Descriptor instead.
func (ProtoPolyType) EnumDescriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{0}
}

//
//ProtoValue represents a single value supported by the DBMS.
//It contains a wide range of fields each corresponding to one supported data type.
//Only one field can be set at a time.
type ProtoValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*ProtoValue_Boolean
	//	*ProtoValue_Integer
	//	*ProtoValue_Long
	//	*ProtoValue_BigDecimal
	//	*ProtoValue_Float
	//	*ProtoValue_Double
	//	*ProtoValue_Date
	//	*ProtoValue_Time
	//	*ProtoValue_Timestamp
	//	*ProtoValue_Interval
	//	*ProtoValue_String_
	//	*ProtoValue_Binary
	//	*ProtoValue_Null
	//	*ProtoValue_List
	//	*ProtoValue_Document
	//	*ProtoValue_File
	Value isProtoValue_Value `protobuf_oneof:"value"`
}

func (x *ProtoValue) Reset() {
	*x = ProtoValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoValue) ProtoMessage() {}

func (x *ProtoValue) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoValue.ProtoReflect.Descriptor instead.
func (*ProtoValue) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{0}
}

func (m *ProtoValue) GetValue() isProtoValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *ProtoValue) GetBoolean() *ProtoBoolean {
	if x, ok := x.GetValue().(*ProtoValue_Boolean); ok {
		return x.Boolean
	}
	return nil
}

func (x *ProtoValue) GetInteger() *ProtoInteger {
	if x, ok := x.GetValue().(*ProtoValue_Integer); ok {
		return x.Integer
	}
	return nil
}

func (x *ProtoValue) GetLong() *ProtoLong {
	if x, ok := x.GetValue().(*ProtoValue_Long); ok {
		return x.Long
	}
	return nil
}

func (x *ProtoValue) GetBigDecimal() *ProtoBigDecimal {
	if x, ok := x.GetValue().(*ProtoValue_BigDecimal); ok {
		return x.BigDecimal
	}
	return nil
}

func (x *ProtoValue) GetFloat() *ProtoFloat {
	if x, ok := x.GetValue().(*ProtoValue_Float); ok {
		return x.Float
	}
	return nil
}

func (x *ProtoValue) GetDouble() *ProtoDouble {
	if x, ok := x.GetValue().(*ProtoValue_Double); ok {
		return x.Double
	}
	return nil
}

func (x *ProtoValue) GetDate() *ProtoDate {
	if x, ok := x.GetValue().(*ProtoValue_Date); ok {
		return x.Date
	}
	return nil
}

func (x *ProtoValue) GetTime() *ProtoTime {
	if x, ok := x.GetValue().(*ProtoValue_Time); ok {
		return x.Time
	}
	return nil
}

func (x *ProtoValue) GetTimestamp() *ProtoTimestamp {
	if x, ok := x.GetValue().(*ProtoValue_Timestamp); ok {
		return x.Timestamp
	}
	return nil
}

func (x *ProtoValue) GetInterval() *ProtoInterval {
	if x, ok := x.GetValue().(*ProtoValue_Interval); ok {
		return x.Interval
	}
	return nil
}

func (x *ProtoValue) GetString_() *ProtoString {
	if x, ok := x.GetValue().(*ProtoValue_String_); ok {
		return x.String_
	}
	return nil
}

func (x *ProtoValue) GetBinary() *ProtoBinary {
	if x, ok := x.GetValue().(*ProtoValue_Binary); ok {
		return x.Binary
	}
	return nil
}

func (x *ProtoValue) GetNull() *ProtoNull {
	if x, ok := x.GetValue().(*ProtoValue_Null); ok {
		return x.Null
	}
	return nil
}

func (x *ProtoValue) GetList() *ProtoList {
	if x, ok := x.GetValue().(*ProtoValue_List); ok {
		return x.List
	}
	return nil
}

func (x *ProtoValue) GetDocument() *ProtoDocument {
	if x, ok := x.GetValue().(*ProtoValue_Document); ok {
		return x.Document
	}
	return nil
}

func (x *ProtoValue) GetFile() *ProtoFile {
	if x, ok := x.GetValue().(*ProtoValue_File); ok {
		return x.File
	}
	return nil
}

type isProtoValue_Value interface {
	isProtoValue_Value()
}

type ProtoValue_Boolean struct {
	// Field used to represent a boolean. If set, all other fields must be empty.
	Boolean *ProtoBoolean `protobuf:"bytes,1,opt,name=boolean,proto3,oneof"`
}

type ProtoValue_Integer struct {
	// Field used to represent an integer of 32 bits.. If set, all other fields must be empty.
	Integer *ProtoInteger `protobuf:"bytes,2,opt,name=integer,proto3,oneof"`
}

type ProtoValue_Long struct {
	// Field used to represent a long integer of 64 bits. If set, all other fields must be empty.
	Long *ProtoLong `protobuf:"bytes,3,opt,name=long,proto3,oneof"`
}

type ProtoValue_BigDecimal struct {
	// Field used to represent a BigDecimal. The value is represented using an unscaled value (arbitrary length byte string), scale (32bit) and precision (32bit). If set, all other fields must be empty.
	BigDecimal *ProtoBigDecimal `protobuf:"bytes,12,opt,name=big_decimal,json=bigDecimal,proto3,oneof"`
}

type ProtoValue_Float struct {
	// Field used to represent a floating-point number of 32 bits. If set, all other fields must be empty.
	Float *ProtoFloat `protobuf:"bytes,7,opt,name=float,proto3,oneof"`
}

type ProtoValue_Double struct {
	// Field used to represent a double-precision (64 bit) floating-point number. If set, all other fields must be empty.
	Double *ProtoDouble `protobuf:"bytes,6,opt,name=double,proto3,oneof"`
}

type ProtoValue_Date struct {
	// Field used to represent a date. Dates are stored in days since epoch till the start of the specified day. If set, all other fields must be empty.
	Date *ProtoDate `protobuf:"bytes,5,opt,name=date,proto3,oneof"`
}

type ProtoValue_Time struct {
	// Field used to represent a time. The value is specified as milliseconds since midnight of a day. If set, all other fields must be empty.
	Time *ProtoTime `protobuf:"bytes,9,opt,name=time,proto3,oneof"`
}

type ProtoValue_Timestamp struct {
	// Field used to represent a timestamp. The value is specified as milliseconds since epoch. If set, all other fields must be empty.
	Timestamp *ProtoTimestamp `protobuf:"bytes,10,opt,name=timestamp,proto3,oneof"`
}

type ProtoValue_Interval struct {
	// Field used to represent a time interval. Intervals are either specified in milliseconds or months. The unit is specified along the value. If set, all other fields must be empty.
	Interval *ProtoInterval `protobuf:"bytes,13,opt,name=interval,proto3,oneof"`
}

type ProtoValue_String_ struct {
	// Field used to represent an string of arbitrary length. If set, all other fields must be empty.
	String_ *ProtoString `protobuf:"bytes,8,opt,name=string,proto3,oneof"`
}

type ProtoValue_Binary struct {
	// Field used to represent binary data of arbitrary length. If set, all other fields must be empty.
	Binary *ProtoBinary `protobuf:"bytes,4,opt,name=binary,proto3,oneof"`
}

type ProtoValue_Null struct {
	// Field used to represent a null value. If set, all other fields must be empty.
	Null *ProtoNull `protobuf:"bytes,11,opt,name=null,proto3,oneof"`
}

type ProtoValue_List struct {
	// Field used to represent a list of ProtoValues. If set, all other fields must be empty.
	List *ProtoList `protobuf:"bytes,16,opt,name=list,proto3,oneof"`
}

type ProtoValue_Document struct {
	// Field used to represent a document consisting of key value pairs where keys and values are arbitrary ProtoValues. If set, all other fields must be empty.
	Document *ProtoDocument `protobuf:"bytes,18,opt,name=document,proto3,oneof"`
}

type ProtoValue_File struct {
	// Field used to represent a FILE type such as FILE, IMAGE, VIDEO or AUDIO.
	File *ProtoFile `protobuf:"bytes,19,opt,name=file,proto3,oneof"`
}

func (*ProtoValue_Boolean) isProtoValue_Value() {}

func (*ProtoValue_Integer) isProtoValue_Value() {}

func (*ProtoValue_Long) isProtoValue_Value() {}

func (*ProtoValue_BigDecimal) isProtoValue_Value() {}

func (*ProtoValue_Float) isProtoValue_Value() {}

func (*ProtoValue_Double) isProtoValue_Value() {}

func (*ProtoValue_Date) isProtoValue_Value() {}

func (*ProtoValue_Time) isProtoValue_Value() {}

func (*ProtoValue_Timestamp) isProtoValue_Value() {}

func (*ProtoValue_Interval) isProtoValue_Value() {}

func (*ProtoValue_String_) isProtoValue_Value() {}

func (*ProtoValue_Binary) isProtoValue_Value() {}

func (*ProtoValue_Null) isProtoValue_Value() {}

func (*ProtoValue_List) isProtoValue_Value() {}

func (*ProtoValue_Document) isProtoValue_Value() {}

func (*ProtoValue_File) isProtoValue_Value() {}

//
//Represents a boolean value.
type ProtoBoolean struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A boolean value.
	Boolean bool `protobuf:"varint,1,opt,name=boolean,proto3" json:"boolean,omitempty"`
}

func (x *ProtoBoolean) Reset() {
	*x = ProtoBoolean{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoBoolean) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBoolean) ProtoMessage() {}

func (x *ProtoBoolean) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBoolean.ProtoReflect.Descriptor instead.
func (*ProtoBoolean) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoBoolean) GetBoolean() bool {
	if x != nil {
		return x.Boolean
	}
	return false
}

//
//Represents a 32-bit integer value.
type ProtoInteger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A 32-bit integer value.
	Integer int32 `protobuf:"varint,1,opt,name=integer,proto3" json:"integer,omitempty"`
}

func (x *ProtoInteger) Reset() {
	*x = ProtoInteger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoInteger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoInteger) ProtoMessage() {}

func (x *ProtoInteger) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoInteger.ProtoReflect.Descriptor instead.
func (*ProtoInteger) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoInteger) GetInteger() int32 {
	if x != nil {
		return x.Integer
	}
	return 0
}

//
//Represents a 64-bit long integer value.
type ProtoLong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A 64-bit long integer value.
	Long int64 `protobuf:"varint,1,opt,name=long,proto3" json:"long,omitempty"`
}

func (x *ProtoLong) Reset() {
	*x = ProtoLong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoLong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoLong) ProtoMessage() {}

func (x *ProtoLong) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoLong.ProtoReflect.Descriptor instead.
func (*ProtoLong) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoLong) GetLong() int64 {
	if x != nil {
		return x.Long
	}
	return 0
}

//
//Represents a BigDecimal value with specified precision and scale.
//The value is reconstructed by calculating unscaled_value * 10 ^ -scale.
type ProtoBigDecimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The scale of the BigDecimal.
	Scale int32 `protobuf:"varint,1,opt,name=scale,proto3" json:"scale,omitempty"`
	// The unscaled value of the BigDecimal.
	UnscaledValue []byte `protobuf:"bytes,3,opt,name=unscaled_value,json=unscaledValue,proto3" json:"unscaled_value,omitempty"`
}

func (x *ProtoBigDecimal) Reset() {
	*x = ProtoBigDecimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoBigDecimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBigDecimal) ProtoMessage() {}

func (x *ProtoBigDecimal) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBigDecimal.ProtoReflect.Descriptor instead.
func (*ProtoBigDecimal) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{4}
}

func (x *ProtoBigDecimal) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ProtoBigDecimal) GetUnscaledValue() []byte {
	if x != nil {
		return x.UnscaledValue
	}
	return nil
}

//
//Represents a single precision floating point number.
type ProtoFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A single precision floating point number.
	Float float32 `protobuf:"fixed32,1,opt,name=float,proto3" json:"float,omitempty"`
}

func (x *ProtoFloat) Reset() {
	*x = ProtoFloat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFloat) ProtoMessage() {}

func (x *ProtoFloat) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFloat.ProtoReflect.Descriptor instead.
func (*ProtoFloat) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{5}
}

func (x *ProtoFloat) GetFloat() float32 {
	if x != nil {
		return x.Float
	}
	return 0
}

//
//Represents a double precision floating point number.
type ProtoDouble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A double precision floating point number.
	Double float64 `protobuf:"fixed64,1,opt,name=double,proto3" json:"double,omitempty"`
}

func (x *ProtoDouble) Reset() {
	*x = ProtoDouble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoDouble) ProtoMessage() {}

func (x *ProtoDouble) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoDouble.ProtoReflect.Descriptor instead.
func (*ProtoDouble) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{6}
}

func (x *ProtoDouble) GetDouble() float64 {
	if x != nil {
		return x.Double
	}
	return 0
}

//
//Represents a date as a 64-bit integer.
type ProtoDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Days since epoch till start of the specified day.
	Date int64 `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *ProtoDate) Reset() {
	*x = ProtoDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoDate) ProtoMessage() {}

func (x *ProtoDate) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoDate.ProtoReflect.Descriptor instead.
func (*ProtoDate) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{7}
}

func (x *ProtoDate) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

//
//Represents a time value.
type ProtoTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Milliseconds since midnight of an arbitrary day.
	Time int32 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *ProtoTime) Reset() {
	*x = ProtoTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTime) ProtoMessage() {}

func (x *ProtoTime) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTime.ProtoReflect.Descriptor instead.
func (*ProtoTime) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{8}
}

func (x *ProtoTime) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

//
//Represents a timestamp value.
type ProtoTimestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The timestamp value in milliseconds since epoch.
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ProtoTimestamp) Reset() {
	*x = ProtoTimestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTimestamp) ProtoMessage() {}

func (x *ProtoTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTimestamp.ProtoReflect.Descriptor instead.
func (*ProtoTimestamp) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{9}
}

func (x *ProtoTimestamp) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

//
//Represents an interval value.
type ProtoInterval struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Milliseconds int64 `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	Months       int64 `protobuf:"varint,2,opt,name=months,proto3" json:"months,omitempty"`
}

func (x *ProtoInterval) Reset() {
	*x = ProtoInterval{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoInterval) ProtoMessage() {}

func (x *ProtoInterval) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoInterval.ProtoReflect.Descriptor instead.
func (*ProtoInterval) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{10}
}

func (x *ProtoInterval) GetMilliseconds() int64 {
	if x != nil {
		return x.Milliseconds
	}
	return 0
}

func (x *ProtoInterval) GetMonths() int64 {
	if x != nil {
		return x.Months
	}
	return 0
}

//
//Represents a string value.
type ProtoString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A string value of arbitrary length.
	String_ string `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
}

func (x *ProtoString) Reset() {
	*x = ProtoString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoString) ProtoMessage() {}

func (x *ProtoString) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoString.ProtoReflect.Descriptor instead.
func (*ProtoString) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{11}
}

func (x *ProtoString) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

//
//Represents binary data.
type ProtoBinary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Binary data of arbitrary length.
	Binary []byte `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *ProtoBinary) Reset() {
	*x = ProtoBinary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoBinary) ProtoMessage() {}

func (x *ProtoBinary) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoBinary.ProtoReflect.Descriptor instead.
func (*ProtoBinary) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{12}
}

func (x *ProtoBinary) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

//
//Represents a null value. This message does not contain any fields.
type ProtoNull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProtoNull) Reset() {
	*x = ProtoNull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoNull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoNull) ProtoMessage() {}

func (x *ProtoNull) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoNull.ProtoReflect.Descriptor instead.
func (*ProtoNull) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{13}
}

//
//Represents a list of ProtoValue items.
type ProtoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of ProtoValue items.
	Values []*ProtoValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ProtoList) Reset() {
	*x = ProtoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoList) ProtoMessage() {}

func (x *ProtoList) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoList.ProtoReflect.Descriptor instead.
func (*ProtoList) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{14}
}

func (x *ProtoList) GetValues() []*ProtoValue {
	if x != nil {
		return x.Values
	}
	return nil
}

//
//Defines a key-value pair using ProtoValues for both key and value.
type ProtoEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The key of the entry.
	Key *ProtoValue `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value of the entry.
	Value *ProtoValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ProtoEntry) Reset() {
	*x = ProtoEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoEntry) ProtoMessage() {}

func (x *ProtoEntry) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoEntry.ProtoReflect.Descriptor instead.
func (*ProtoEntry) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{15}
}

func (x *ProtoEntry) GetKey() *ProtoValue {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ProtoEntry) GetValue() *ProtoValue {
	if x != nil {
		return x.Value
	}
	return nil
}

//
//Represents a document consisting of multiple ProtoEntry items.
type ProtoDocument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of ProtoEntry items forming the document.
	Entries []*ProtoEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *ProtoDocument) Reset() {
	*x = ProtoDocument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoDocument) ProtoMessage() {}

func (x *ProtoDocument) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoDocument.ProtoReflect.Descriptor instead.
func (*ProtoDocument) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{16}
}

func (x *ProtoDocument) GetEntries() []*ProtoEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

//
//Represents a file containing large binary data.
type ProtoFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The content of the file in binary.
	Binary []byte `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
}

func (x *ProtoFile) Reset() {
	*x = ProtoFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_value_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoFile) ProtoMessage() {}

func (x *ProtoFile) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_value_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoFile.ProtoReflect.Descriptor instead.
func (*ProtoFile) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_value_proto_rawDescGZIP(), []int{17}
}

func (x *ProtoFile) GetBinary() []byte {
	if x != nil {
		return x.Binary
	}
	return nil
}

var File_org_polypheny_prism_value_proto protoreflect.FileDescriptor

var file_org_polypheny_prism_value_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x22, 0xd6, 0x07, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3d, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c,
	0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f,
	0x6c, 0x65, 0x61, 0x6e, 0x12, 0x3d, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79,
	0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x6f, 0x6e,
	0x67, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x47, 0x0a, 0x0b, 0x62, 0x69, 0x67,
	0x5f, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x69, 0x67, 0x44, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x69, 0x67, 0x44, 0x65, 0x63, 0x69, 0x6d,
	0x61, 0x6c, 0x12, 0x37, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x48, 0x00, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x3a, 0x0a, 0x06, 0x64,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x48, 0x00, 0x52,
	0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79,
	0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x44, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x43, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c,
	0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x40, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x48, 0x00,
	0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x3a, 0x0a, 0x06, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x3a, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c,
	0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x12, 0x34, 0x0a, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4e, 0x75, 0x6c, 0x6c,
	0x48, 0x00, 0x52, 0x04, 0x6e, 0x75, 0x6c, 0x6c, 0x12, 0x34, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c,
	0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x40,
	0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x34, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00,
	0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x28, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x22, 0x28, 0x0a, 0x0c, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x74,
	0x65, 0x67, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x65,
	0x67, 0x65, 0x72, 0x22, 0x1f, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4c, 0x6f, 0x6e, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x6c, 0x6f, 0x6e, 0x67, 0x22, 0x4e, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x69, 0x67,
	0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x25, 0x0a,
	0x0e, 0x75, 0x6e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x75, 0x6e, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x6c, 0x6f,
	0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x22, 0x25, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x22,
	0x1f, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x22, 0x1f, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x22, 0x2e, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x22, 0x4b, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x73, 0x22, 0x25,
	0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x25, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x22, 0x0b, 0x0a, 0x09,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x44, 0x0a, 0x09, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c,
	0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0x76, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x31, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d,
	0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x35, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4a, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72,
	0x69, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2a, 0xbb, 0x04, 0x0a, 0x0d, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x6f, 0x6c, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e,
	0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x42,
	0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x49, 0x4e, 0x59,
	0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x4d, 0x41, 0x4c, 0x4c, 0x49, 0x4e,
	0x54, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x10, 0x04,
	0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x47, 0x49, 0x4e, 0x54, 0x10, 0x05, 0x12, 0x0b, 0x0a, 0x07,
	0x44, 0x45, 0x43, 0x49, 0x4d, 0x41, 0x4c, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41,
	0x4c, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10, 0x08, 0x12, 0x0a,
	0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x10, 0x09, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41,
	0x54, 0x45, 0x10, 0x0a, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x0b, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x10, 0x0d, 0x12, 0x0c, 0x0a,
	0x08, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x56, 0x41, 0x4c, 0x10, 0x0f, 0x12, 0x08, 0x0a, 0x04, 0x43,
	0x48, 0x41, 0x52, 0x10, 0x1c, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x41, 0x52, 0x43, 0x48, 0x41, 0x52,
	0x10, 0x1d, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x3a, 0x12, 0x0a, 0x0a, 0x06,
	0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x1e, 0x12, 0x0d, 0x0a, 0x09, 0x56, 0x41, 0x52, 0x42,
	0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x1f, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10,
	0x20, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x21, 0x12, 0x07, 0x0a, 0x03,
	0x4d, 0x41, 0x50, 0x10, 0x22, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x4f, 0x43, 0x55, 0x4d, 0x45, 0x4e,
	0x54, 0x10, 0x23, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x41, 0x50, 0x48, 0x10, 0x24, 0x12, 0x08,
	0x0a, 0x04, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x25, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x44, 0x47, 0x45,
	0x10, 0x26, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x41, 0x54, 0x48, 0x10, 0x27, 0x12, 0x09, 0x0a, 0x05,
	0x49, 0x4d, 0x41, 0x47, 0x45, 0x10, 0x28, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f,
	0x10, 0x29, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x55, 0x44, 0x49, 0x4f, 0x10, 0x2a, 0x12, 0x08, 0x0a,
	0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x2b, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x54, 0x49,
	0x4e, 0x43, 0x54, 0x10, 0x2c, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x52, 0x55, 0x43, 0x54, 0x55,
	0x52, 0x45, 0x44, 0x10, 0x2d, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x4f, 0x57, 0x10, 0x2e, 0x12, 0x09,
	0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x2f, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x55, 0x52,
	0x53, 0x4f, 0x52, 0x10, 0x30, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f,
	0x4c, 0x49, 0x53, 0x54, 0x10, 0x31, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x59, 0x4e, 0x41, 0x4d, 0x49,
	0x43, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x10, 0x32, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x45, 0x4f, 0x4d,
	0x45, 0x54, 0x52, 0x59, 0x10, 0x33, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x4d, 0x42, 0x4f, 0x4c,
	0x10, 0x34, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10, 0x35, 0x12, 0x0c, 0x0a, 0x08,
	0x4d, 0x55, 0x4c, 0x54, 0x49, 0x53, 0x45, 0x54, 0x10, 0x36, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4e,
	0x59, 0x10, 0x37, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x44, 0x45, 0x46, 0x49,
	0x4e, 0x45, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x38, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x4f,
	0x57, 0x5f, 0x49, 0x44, 0x10, 0x39, 0x42, 0x55, 0x0a, 0x13, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f,
	0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x42, 0x0f, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x19, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x3b, 0x70, 0x72, 0x69, 0x73, 0x6d, 0xaa, 0x02, 0x0f, 0x50, 0x6f,
	0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x50, 0x72, 0x69, 0x73, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_polypheny_prism_value_proto_rawDescOnce sync.Once
	file_org_polypheny_prism_value_proto_rawDescData = file_org_polypheny_prism_value_proto_rawDesc
)

func file_org_polypheny_prism_value_proto_rawDescGZIP() []byte {
	file_org_polypheny_prism_value_proto_rawDescOnce.Do(func() {
		file_org_polypheny_prism_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_polypheny_prism_value_proto_rawDescData)
	})
	return file_org_polypheny_prism_value_proto_rawDescData
}

var file_org_polypheny_prism_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_org_polypheny_prism_value_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_org_polypheny_prism_value_proto_goTypes = []interface{}{
	(ProtoPolyType)(0),      // 0: org.polypheny.prism.ProtoPolyType
	(*ProtoValue)(nil),      // 1: org.polypheny.prism.ProtoValue
	(*ProtoBoolean)(nil),    // 2: org.polypheny.prism.ProtoBoolean
	(*ProtoInteger)(nil),    // 3: org.polypheny.prism.ProtoInteger
	(*ProtoLong)(nil),       // 4: org.polypheny.prism.ProtoLong
	(*ProtoBigDecimal)(nil), // 5: org.polypheny.prism.ProtoBigDecimal
	(*ProtoFloat)(nil),      // 6: org.polypheny.prism.ProtoFloat
	(*ProtoDouble)(nil),     // 7: org.polypheny.prism.ProtoDouble
	(*ProtoDate)(nil),       // 8: org.polypheny.prism.ProtoDate
	(*ProtoTime)(nil),       // 9: org.polypheny.prism.ProtoTime
	(*ProtoTimestamp)(nil),  // 10: org.polypheny.prism.ProtoTimestamp
	(*ProtoInterval)(nil),   // 11: org.polypheny.prism.ProtoInterval
	(*ProtoString)(nil),     // 12: org.polypheny.prism.ProtoString
	(*ProtoBinary)(nil),     // 13: org.polypheny.prism.ProtoBinary
	(*ProtoNull)(nil),       // 14: org.polypheny.prism.ProtoNull
	(*ProtoList)(nil),       // 15: org.polypheny.prism.ProtoList
	(*ProtoEntry)(nil),      // 16: org.polypheny.prism.ProtoEntry
	(*ProtoDocument)(nil),   // 17: org.polypheny.prism.ProtoDocument
	(*ProtoFile)(nil),       // 18: org.polypheny.prism.ProtoFile
}
var file_org_polypheny_prism_value_proto_depIdxs = []int32{
	2,  // 0: org.polypheny.prism.ProtoValue.boolean:type_name -> org.polypheny.prism.ProtoBoolean
	3,  // 1: org.polypheny.prism.ProtoValue.integer:type_name -> org.polypheny.prism.ProtoInteger
	4,  // 2: org.polypheny.prism.ProtoValue.long:type_name -> org.polypheny.prism.ProtoLong
	5,  // 3: org.polypheny.prism.ProtoValue.big_decimal:type_name -> org.polypheny.prism.ProtoBigDecimal
	6,  // 4: org.polypheny.prism.ProtoValue.float:type_name -> org.polypheny.prism.ProtoFloat
	7,  // 5: org.polypheny.prism.ProtoValue.double:type_name -> org.polypheny.prism.ProtoDouble
	8,  // 6: org.polypheny.prism.ProtoValue.date:type_name -> org.polypheny.prism.ProtoDate
	9,  // 7: org.polypheny.prism.ProtoValue.time:type_name -> org.polypheny.prism.ProtoTime
	10, // 8: org.polypheny.prism.ProtoValue.timestamp:type_name -> org.polypheny.prism.ProtoTimestamp
	11, // 9: org.polypheny.prism.ProtoValue.interval:type_name -> org.polypheny.prism.ProtoInterval
	12, // 10: org.polypheny.prism.ProtoValue.string:type_name -> org.polypheny.prism.ProtoString
	13, // 11: org.polypheny.prism.ProtoValue.binary:type_name -> org.polypheny.prism.ProtoBinary
	14, // 12: org.polypheny.prism.ProtoValue.null:type_name -> org.polypheny.prism.ProtoNull
	15, // 13: org.polypheny.prism.ProtoValue.list:type_name -> org.polypheny.prism.ProtoList
	17, // 14: org.polypheny.prism.ProtoValue.document:type_name -> org.polypheny.prism.ProtoDocument
	18, // 15: org.polypheny.prism.ProtoValue.file:type_name -> org.polypheny.prism.ProtoFile
	1,  // 16: org.polypheny.prism.ProtoList.values:type_name -> org.polypheny.prism.ProtoValue
	1,  // 17: org.polypheny.prism.ProtoEntry.key:type_name -> org.polypheny.prism.ProtoValue
	1,  // 18: org.polypheny.prism.ProtoEntry.value:type_name -> org.polypheny.prism.ProtoValue
	16, // 19: org.polypheny.prism.ProtoDocument.entries:type_name -> org.polypheny.prism.ProtoEntry
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_org_polypheny_prism_value_proto_init() }
func file_org_polypheny_prism_value_proto_init() {
	if File_org_polypheny_prism_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_org_polypheny_prism_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoBoolean); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoInteger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoLong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoBigDecimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoFloat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoDouble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoTimestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoInterval); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoBinary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoNull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoDocument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_value_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_org_polypheny_prism_value_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ProtoValue_Boolean)(nil),
		(*ProtoValue_Integer)(nil),
		(*ProtoValue_Long)(nil),
		(*ProtoValue_BigDecimal)(nil),
		(*ProtoValue_Float)(nil),
		(*ProtoValue_Double)(nil),
		(*ProtoValue_Date)(nil),
		(*ProtoValue_Time)(nil),
		(*ProtoValue_Timestamp)(nil),
		(*ProtoValue_Interval)(nil),
		(*ProtoValue_String_)(nil),
		(*ProtoValue_Binary)(nil),
		(*ProtoValue_Null)(nil),
		(*ProtoValue_List)(nil),
		(*ProtoValue_Document)(nil),
		(*ProtoValue_File)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_polypheny_prism_value_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_polypheny_prism_value_proto_goTypes,
		DependencyIndexes: file_org_polypheny_prism_value_proto_depIdxs,
		EnumInfos:         file_org_polypheny_prism_value_proto_enumTypes,
		MessageInfos:      file_org_polypheny_prism_value_proto_msgTypes,
	}.Build()
	File_org_polypheny_prism_value_proto = out.File
	file_org_polypheny_prism_value_proto_rawDesc = nil
	file_org_polypheny_prism_value_proto_goTypes = nil
	file_org_polypheny_prism_value_proto_depIdxs = nil
}
