//
//Messages that are used for querying general metadata.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.3
// source: org/polypheny/prism/meta_responses.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The return type enum is part of the message Procedure and indicates the possible types of return values for a stored procedure.
type Procedure_ReturnType int32

const (
	// Indicates that the return type is unspecified.
	Procedure_UNSPECIFIED Procedure_ReturnType = 0
	// Indicates that the return type is unknown.
	Procedure_UNKNOWN Procedure_ReturnType = 1
	// The procedure does not return a result.
	Procedure_NO_RESULT Procedure_ReturnType = 2
	// The procedure returns a result.
	Procedure_RESULT Procedure_ReturnType = 3
)

// Enum value maps for Procedure_ReturnType.
var (
	Procedure_ReturnType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNKNOWN",
		2: "NO_RESULT",
		3: "RESULT",
	}
	Procedure_ReturnType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"UNKNOWN":     1,
		"NO_RESULT":   2,
		"RESULT":      3,
	}
)

func (x Procedure_ReturnType) Enum() *Procedure_ReturnType {
	p := new(Procedure_ReturnType)
	*p = x
	return p
}

func (x Procedure_ReturnType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Procedure_ReturnType) Descriptor() protoreflect.EnumDescriptor {
	return file_org_polypheny_prism_meta_responses_proto_enumTypes[0].Descriptor()
}

func (Procedure_ReturnType) Type() protoreflect.EnumType {
	return &file_org_polypheny_prism_meta_responses_proto_enumTypes[0]
}

func (x Procedure_ReturnType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Procedure_ReturnType.Descriptor instead.
func (Procedure_ReturnType) EnumDescriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{10, 0}
}

// The DbmsVersionResponse message relays details about the version and name of the database management system (DBMS) in response to a DbmsVersionRequest.
type DbmsVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the database management system.
	DbmsName string `protobuf:"bytes,1,opt,name=dbms_name,json=dbmsName,proto3" json:"dbms_name,omitempty"`
	// The full version name of the DBMS.
	VersionName string `protobuf:"bytes,2,opt,name=version_name,json=versionName,proto3" json:"version_name,omitempty"`
	// The major version number of the DBMS.
	MajorVersion int32 `protobuf:"varint,3,opt,name=major_version,json=majorVersion,proto3" json:"major_version,omitempty"`
	// The minor version number of the DBMS.
	MinorVersion int32 `protobuf:"varint,4,opt,name=minor_version,json=minorVersion,proto3" json:"minor_version,omitempty"`
}

func (x *DbmsVersionResponse) Reset() {
	*x = DbmsVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DbmsVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DbmsVersionResponse) ProtoMessage() {}

func (x *DbmsVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DbmsVersionResponse.ProtoReflect.Descriptor instead.
func (*DbmsVersionResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{0}
}

func (x *DbmsVersionResponse) GetDbmsName() string {
	if x != nil {
		return x.DbmsName
	}
	return ""
}

func (x *DbmsVersionResponse) GetVersionName() string {
	if x != nil {
		return x.VersionName
	}
	return ""
}

func (x *DbmsVersionResponse) GetMajorVersion() int32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *DbmsVersionResponse) GetMinorVersion() int32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

// The default namespace
type DefaultNamespaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DefaultNamespace string `protobuf:"bytes,1,opt,name=default_namespace,json=defaultNamespace,proto3" json:"default_namespace,omitempty"`
}

func (x *DefaultNamespaceResponse) Reset() {
	*x = DefaultNamespaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultNamespaceResponse) ProtoMessage() {}

func (x *DefaultNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultNamespaceResponse.ProtoReflect.Descriptor instead.
func (*DefaultNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultNamespaceResponse) GetDefaultNamespace() string {
	if x != nil {
		return x.DefaultNamespace
	}
	return ""
}

// The TableTypesResponse message conveys information about the various table types present in the system.
type TableTypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of TableType objects detailing each table type present in the system.
	TableTypes []*TableType `protobuf:"bytes,1,rep,name=table_types,json=tableTypes,proto3" json:"table_types,omitempty"`
}

func (x *TableTypesResponse) Reset() {
	*x = TableTypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableTypesResponse) ProtoMessage() {}

func (x *TableTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableTypesResponse.ProtoReflect.Descriptor instead.
func (*TableTypesResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{2}
}

func (x *TableTypesResponse) GetTableTypes() []*TableType {
	if x != nil {
		return x.TableTypes
	}
	return nil
}

// The TableType message delineates the nature or category of a table.
type TableType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A descriptor denoting the type or category of a table, such as “BASE TABLE”, “VIEW”, or any other classification present in the system.
	TableType string `protobuf:"bytes,1,opt,name=table_type,json=tableType,proto3" json:"table_type,omitempty"`
}

func (x *TableType) Reset() {
	*x = TableType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableType) ProtoMessage() {}

func (x *TableType) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableType.ProtoReflect.Descriptor instead.
func (*TableType) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{3}
}

func (x *TableType) GetTableType() string {
	if x != nil {
		return x.TableType
	}
	return ""
}

// The TypesResponse message provides a list of native data types supported by the system.
type TypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of Type objects detailing each native data type supported by the system.
	Types []*Type `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *TypesResponse) Reset() {
	*x = TypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypesResponse) ProtoMessage() {}

func (x *TypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypesResponse.ProtoReflect.Descriptor instead.
func (*TypesResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{4}
}

func (x *TypesResponse) GetTypes() []*Type {
	if x != nil {
		return x.Types
	}
	return nil
}

// The Type message describes the characteristics and specifications of a particular native data type.
type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the data type.
	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	// The number of total digits for numeric types or the maximum length for string and binary types.
	Precision int32 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	// The character(s) used to prefix a literal of this type (e.g., a single quote for strings).
	LiteralPrefix *string `protobuf:"bytes,3,opt,name=literal_prefix,json=literalPrefix,proto3,oneof" json:"literal_prefix,omitempty"`
	// The character(s) used to suffix a literal of this type.
	LiteralSuffix *string `protobuf:"bytes,4,opt,name=literal_suffix,json=literalSuffix,proto3,oneof" json:"literal_suffix,omitempty"`
	// Indicates whether the data type is case sensitive.
	IsCaseSensitive bool `protobuf:"varint,5,opt,name=is_case_sensitive,json=isCaseSensitive,proto3" json:"is_case_sensitive,omitempty"`
	// Indicates how the data type can be used in WHERE clauses.
	IsSearchable int32 `protobuf:"varint,6,opt,name=is_searchable,json=isSearchable,proto3" json:"is_searchable,omitempty"`
	// Indicates whether columns of this data type auto-increment.
	IsAutoIncrement bool `protobuf:"varint,7,opt,name=is_auto_increment,json=isAutoIncrement,proto3" json:"is_auto_increment,omitempty"`
	// The minimum scale for this data type.
	MinScale int32 `protobuf:"varint,8,opt,name=min_scale,json=minScale,proto3" json:"min_scale,omitempty"`
	// The maximum scale for this data type.
	MaxScale int32 `protobuf:"varint,9,opt,name=max_scale,json=maxScale,proto3" json:"max_scale,omitempty"`
	// The base number used in representing numeric values.
	Radix int32 `protobuf:"varint,10,opt,name=radix,proto3" json:"radix,omitempty"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{5}
}

func (x *Type) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *Type) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Type) GetLiteralPrefix() string {
	if x != nil && x.LiteralPrefix != nil {
		return *x.LiteralPrefix
	}
	return ""
}

func (x *Type) GetLiteralSuffix() string {
	if x != nil && x.LiteralSuffix != nil {
		return *x.LiteralSuffix
	}
	return ""
}

func (x *Type) GetIsCaseSensitive() bool {
	if x != nil {
		return x.IsCaseSensitive
	}
	return false
}

func (x *Type) GetIsSearchable() int32 {
	if x != nil {
		return x.IsSearchable
	}
	return 0
}

func (x *Type) GetIsAutoIncrement() bool {
	if x != nil {
		return x.IsAutoIncrement
	}
	return false
}

func (x *Type) GetMinScale() int32 {
	if x != nil {
		return x.MinScale
	}
	return 0
}

func (x *Type) GetMaxScale() int32 {
	if x != nil {
		return x.MaxScale
	}
	return 0
}

func (x *Type) GetRadix() int32 {
	if x != nil {
		return x.Radix
	}
	return 0
}

// The UserDefinedType message encapsulates details about a specific user-defined data type.
type UserDefinedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the user-defined data type.
	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	// A list of ValueMeta objects detailing the metadata associated with fields of this data type.
	ValueMetas []*ValueMeta `protobuf:"bytes,2,rep,name=value_metas,json=valueMetas,proto3" json:"value_metas,omitempty"`
}

func (x *UserDefinedType) Reset() {
	*x = UserDefinedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDefinedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDefinedType) ProtoMessage() {}

func (x *UserDefinedType) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDefinedType.ProtoReflect.Descriptor instead.
func (*UserDefinedType) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{6}
}

func (x *UserDefinedType) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *UserDefinedType) GetValueMetas() []*ValueMeta {
	if x != nil {
		return x.ValueMetas
	}
	return nil
}

// The ValueMeta message offers insights into the metadata of a specific field related to a user-defined type.
type ValueMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name or descriptor of the value’s metadata.
	ValueName string `protobuf:"bytes,1,opt,name=value_name,json=valueName,proto3" json:"value_name,omitempty"`
}

func (x *ValueMeta) Reset() {
	*x = ValueMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueMeta) ProtoMessage() {}

func (x *ValueMeta) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueMeta.ProtoReflect.Descriptor instead.
func (*ValueMeta) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{7}
}

func (x *ValueMeta) GetValueName() string {
	if x != nil {
		return x.ValueName
	}
	return ""
}

// The MetaStringResponse message encapsulates a string that represents some specific metadata information.
type MetaStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A string representing the requested metadata information.
	String_ string `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
}

func (x *MetaStringResponse) Reset() {
	*x = MetaStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaStringResponse) ProtoMessage() {}

func (x *MetaStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaStringResponse.ProtoReflect.Descriptor instead.
func (*MetaStringResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{8}
}

func (x *MetaStringResponse) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

// The ProceduresResponse message provides a list of stored procedures available within the system.
type ProceduresResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of Procedure objects detailing each stored procedure present in the system.
	Procedures []*Procedure `protobuf:"bytes,1,rep,name=procedures,proto3" json:"procedures,omitempty"`
}

func (x *ProceduresResponse) Reset() {
	*x = ProceduresResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProceduresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProceduresResponse) ProtoMessage() {}

func (x *ProceduresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProceduresResponse.ProtoReflect.Descriptor instead.
func (*ProceduresResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{9}
}

func (x *ProceduresResponse) GetProcedures() []*Procedure {
	if x != nil {
		return x.Procedures
	}
	return nil
}

// The Procedure message encapsulates details about a specific stored procedure in the system.
type Procedure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The simple name of the procedure.
	TrivialName string `protobuf:"bytes,1,opt,name=trivial_name,json=trivialName,proto3" json:"trivial_name,omitempty"`
	// The input parameters required by the procedure.
	InputParameters string `protobuf:"bytes,2,opt,name=input_parameters,json=inputParameters,proto3" json:"input_parameters,omitempty"`
	// A brief description or purpose of the procedure.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Enum indicating the return type of the procedure. It can be unspecified, unknown, no result, or result.
	ReturnType Procedure_ReturnType `protobuf:"varint,4,opt,name=return_type,json=returnType,proto3,enum=org.polypheny.prism.Procedure_ReturnType" json:"return_type,omitempty"`
	// A unique name or identifier for the procedure.
	UniqueName string `protobuf:"bytes,5,opt,name=unique_name,json=uniqueName,proto3" json:"unique_name,omitempty"`
}

func (x *Procedure) Reset() {
	*x = Procedure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Procedure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Procedure) ProtoMessage() {}

func (x *Procedure) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Procedure.ProtoReflect.Descriptor instead.
func (*Procedure) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{10}
}

func (x *Procedure) GetTrivialName() string {
	if x != nil {
		return x.TrivialName
	}
	return ""
}

func (x *Procedure) GetInputParameters() string {
	if x != nil {
		return x.InputParameters
	}
	return ""
}

func (x *Procedure) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Procedure) GetReturnType() Procedure_ReturnType {
	if x != nil {
		return x.ReturnType
	}
	return Procedure_UNSPECIFIED
}

func (x *Procedure) GetUniqueName() string {
	if x != nil {
		return x.UniqueName
	}
	return ""
}

// The ClientInfoProperties message encapsulates key-value pairs representing client-specific information.
type ClientInfoProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A mapping of property names to their corresponding values, providing insights or settings related to the client.
	Properties map[string]string `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ClientInfoProperties) Reset() {
	*x = ClientInfoProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfoProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfoProperties) ProtoMessage() {}

func (x *ClientInfoProperties) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfoProperties.ProtoReflect.Descriptor instead.
func (*ClientInfoProperties) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{11}
}

func (x *ClientInfoProperties) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

// The ClientInfoPropertyResponse message provides metadata about various client-specific properties.
type ClientInfoPropertiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientInfoPropertiesResponse) Reset() {
	*x = ClientInfoPropertiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfoPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfoPropertiesResponse) ProtoMessage() {}

func (x *ClientInfoPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfoPropertiesResponse.ProtoReflect.Descriptor instead.
func (*ClientInfoPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{12}
}

// The ClientInfoPropertyMetaResponse message provides metadata about various client-specific properties.
type ClientInfoPropertyMetaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of ClientInfoPropertyMeta objects detailing metadata for each client-specific property.
	ClientInfoPropertyMetas []*ClientInfoPropertyMeta `protobuf:"bytes,1,rep,name=client_info_property_metas,json=clientInfoPropertyMetas,proto3" json:"client_info_property_metas,omitempty"`
}

func (x *ClientInfoPropertyMetaResponse) Reset() {
	*x = ClientInfoPropertyMetaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfoPropertyMetaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfoPropertyMetaResponse) ProtoMessage() {}

func (x *ClientInfoPropertyMetaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfoPropertyMetaResponse.ProtoReflect.Descriptor instead.
func (*ClientInfoPropertyMetaResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{13}
}

func (x *ClientInfoPropertyMetaResponse) GetClientInfoPropertyMetas() []*ClientInfoPropertyMeta {
	if x != nil {
		return x.ClientInfoPropertyMetas
	}
	return nil
}

// The ClientInfoPropertyMeta message encapsulates metadata about a specific client property.
type ClientInfoPropertyMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique key identifier for the client property.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The default value of the property.
	DefaultValue string `protobuf:"bytes,2,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// Maximum length of the property value. Useful for validation purposes.
	Maxlength int32 `protobuf:"varint,3,opt,name=maxlength,proto3" json:"maxlength,omitempty"`
	// A brief description explaining the purpose or usage of the property.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ClientInfoPropertyMeta) Reset() {
	*x = ClientInfoPropertyMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfoPropertyMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfoPropertyMeta) ProtoMessage() {}

func (x *ClientInfoPropertyMeta) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfoPropertyMeta.ProtoReflect.Descriptor instead.
func (*ClientInfoPropertyMeta) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{14}
}

func (x *ClientInfoPropertyMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ClientInfoPropertyMeta) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ClientInfoPropertyMeta) GetMaxlength() int32 {
	if x != nil {
		return x.Maxlength
	}
	return 0
}

func (x *ClientInfoPropertyMeta) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// The FunctionsResponse message provides a list of functions available within the system.
type FunctionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of Function objects detailing each function present in the system.
	Functions []*Function `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
}

func (x *FunctionsResponse) Reset() {
	*x = FunctionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionsResponse) ProtoMessage() {}

func (x *FunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionsResponse.ProtoReflect.Descriptor instead.
func (*FunctionsResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{15}
}

func (x *FunctionsResponse) GetFunctions() []*Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

// The Function message encapsulates details about a specific function in the system.
type Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the function.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The expected syntax for using the function.
	Syntax string `protobuf:"bytes,2,opt,name=syntax,proto3" json:"syntax,omitempty"`
	// The category to which the function belongs. Helps in categorizing functions for better management and understanding.
	FunctionCategory string `protobuf:"bytes,3,opt,name=function_category,json=functionCategory,proto3" json:"function_category,omitempty"`
	// Indicates whether the function is a table function. If true, it means the function returns a table; otherwise, it returns a scalar value.
	IsTableFunction bool `protobuf:"varint,4,opt,name=is_table_function,json=isTableFunction,proto3" json:"is_table_function,omitempty"`
}

func (x *Function) Reset() {
	*x = Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_meta_responses_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Function.ProtoReflect.Descriptor instead.
func (*Function) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_meta_responses_proto_rawDescGZIP(), []int{16}
}

func (x *Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Function) GetSyntax() string {
	if x != nil {
		return x.Syntax
	}
	return ""
}

func (x *Function) GetFunctionCategory() string {
	if x != nil {
		return x.FunctionCategory
	}
	return ""
}

func (x *Function) GetIsTableFunction() bool {
	if x != nil {
		return x.IsTableFunction
	}
	return false
}

var File_org_polypheny_prism_meta_responses_proto protoreflect.FileDescriptor

var file_org_polypheny_prism_meta_responses_proto_rawDesc = []byte{
	0x0a, 0x28, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x6f, 0x72, 0x67, 0x2e,
	0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x22,
	0x9f, 0x01, 0x0a, 0x13, 0x44, 0x62, 0x6d, 0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x62, 0x6d, 0x73, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x62, 0x6d, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x61, 0x6a, 0x6f, 0x72,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d,
	0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x47, 0x0a, 0x18, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x11, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x22, 0x55, 0x0a, 0x12, 0x54, 0x61,
	0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3f, 0x0a, 0x0b, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79,
	0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x2a, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x40, 0x0a,
	0x0d, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72,
	0x69, 0x73, 0x6d, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22,
	0x8c, 0x03, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x0e, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x70,
	0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x6c,
	0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x88, 0x01, 0x01, 0x12,
	0x2a, 0x0a, 0x0e, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x73, 0x75, 0x66, 0x66, 0x69,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0d, 0x6c, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x11, 0x69,
	0x73, 0x5f, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x43, 0x61, 0x73, 0x65, 0x53, 0x65,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x69, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x11,
	0x69, 0x73, 0x5f, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x41, 0x75, 0x74, 0x6f, 0x49,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f,
	0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x69, 0x6e,
	0x53, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x53, 0x63, 0x61,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x64, 0x69, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x72, 0x61, 0x64, 0x69, 0x78, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6c, 0x69, 0x74,
	0x65, 0x72, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x42, 0x11, 0x0a, 0x0f, 0x5f,
	0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x22, 0x6f,
	0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3f,
	0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68,
	0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x22,
	0x2a, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x4d,
	0x65, 0x74, 0x61, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x54, 0x0a, 0x12, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68,
	0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64,
	0x75, 0x72, 0x65, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x73, 0x22,
	0xaf, 0x02, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x72, 0x69, 0x76, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x69, 0x76, 0x69, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x29, 0x0a, 0x10, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a,
	0x0b, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x29, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75,
	0x72, 0x65, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x45, 0x0a, 0x0a, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b,
	0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10,
	0x03, 0x22, 0xb0, 0x01, 0x0a, 0x14, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x59, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x39,
	0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x69, 0x73, 0x6d, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x1e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x1a, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x5f,
	0x6d, 0x65, 0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x17, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4d, 0x65, 0x74, 0x61,
	0x73, 0x22, 0x8f, 0x01, 0x0a, 0x16, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x23,
	0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x50, 0x0a, 0x11, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6e, 0x74, 0x61, 0x78, 0x12, 0x2b,
	0x0a, 0x11, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x11, 0x69,
	0x73, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x73, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x26, 0x0a, 0x13, 0x6f, 0x72, 0x67, 0x2e, 0x70,
	0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x42, 0x0d,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x50, 0x01, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_polypheny_prism_meta_responses_proto_rawDescOnce sync.Once
	file_org_polypheny_prism_meta_responses_proto_rawDescData = file_org_polypheny_prism_meta_responses_proto_rawDesc
)

func file_org_polypheny_prism_meta_responses_proto_rawDescGZIP() []byte {
	file_org_polypheny_prism_meta_responses_proto_rawDescOnce.Do(func() {
		file_org_polypheny_prism_meta_responses_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_polypheny_prism_meta_responses_proto_rawDescData)
	})
	return file_org_polypheny_prism_meta_responses_proto_rawDescData
}

var file_org_polypheny_prism_meta_responses_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_org_polypheny_prism_meta_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_org_polypheny_prism_meta_responses_proto_goTypes = []interface{}{
	(Procedure_ReturnType)(0),              // 0: org.polypheny.prism.Procedure.ReturnType
	(*DbmsVersionResponse)(nil),            // 1: org.polypheny.prism.DbmsVersionResponse
	(*DefaultNamespaceResponse)(nil),       // 2: org.polypheny.prism.DefaultNamespaceResponse
	(*TableTypesResponse)(nil),             // 3: org.polypheny.prism.TableTypesResponse
	(*TableType)(nil),                      // 4: org.polypheny.prism.TableType
	(*TypesResponse)(nil),                  // 5: org.polypheny.prism.TypesResponse
	(*Type)(nil),                           // 6: org.polypheny.prism.Type
	(*UserDefinedType)(nil),                // 7: org.polypheny.prism.UserDefinedType
	(*ValueMeta)(nil),                      // 8: org.polypheny.prism.ValueMeta
	(*MetaStringResponse)(nil),             // 9: org.polypheny.prism.MetaStringResponse
	(*ProceduresResponse)(nil),             // 10: org.polypheny.prism.ProceduresResponse
	(*Procedure)(nil),                      // 11: org.polypheny.prism.Procedure
	(*ClientInfoProperties)(nil),           // 12: org.polypheny.prism.ClientInfoProperties
	(*ClientInfoPropertiesResponse)(nil),   // 13: org.polypheny.prism.ClientInfoPropertiesResponse
	(*ClientInfoPropertyMetaResponse)(nil), // 14: org.polypheny.prism.ClientInfoPropertyMetaResponse
	(*ClientInfoPropertyMeta)(nil),         // 15: org.polypheny.prism.ClientInfoPropertyMeta
	(*FunctionsResponse)(nil),              // 16: org.polypheny.prism.FunctionsResponse
	(*Function)(nil),                       // 17: org.polypheny.prism.Function
	nil,                                    // 18: org.polypheny.prism.ClientInfoProperties.PropertiesEntry
}
var file_org_polypheny_prism_meta_responses_proto_depIdxs = []int32{
	4,  // 0: org.polypheny.prism.TableTypesResponse.table_types:type_name -> org.polypheny.prism.TableType
	6,  // 1: org.polypheny.prism.TypesResponse.types:type_name -> org.polypheny.prism.Type
	8,  // 2: org.polypheny.prism.UserDefinedType.value_metas:type_name -> org.polypheny.prism.ValueMeta
	11, // 3: org.polypheny.prism.ProceduresResponse.procedures:type_name -> org.polypheny.prism.Procedure
	0,  // 4: org.polypheny.prism.Procedure.return_type:type_name -> org.polypheny.prism.Procedure.ReturnType
	18, // 5: org.polypheny.prism.ClientInfoProperties.properties:type_name -> org.polypheny.prism.ClientInfoProperties.PropertiesEntry
	15, // 6: org.polypheny.prism.ClientInfoPropertyMetaResponse.client_info_property_metas:type_name -> org.polypheny.prism.ClientInfoPropertyMeta
	17, // 7: org.polypheny.prism.FunctionsResponse.functions:type_name -> org.polypheny.prism.Function
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_org_polypheny_prism_meta_responses_proto_init() }
func file_org_polypheny_prism_meta_responses_proto_init() {
	if File_org_polypheny_prism_meta_responses_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_org_polypheny_prism_meta_responses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DbmsVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultNamespaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableTypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDefinedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProceduresResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Procedure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfoProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfoPropertiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfoPropertyMetaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfoPropertyMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_meta_responses_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_org_polypheny_prism_meta_responses_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_polypheny_prism_meta_responses_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_polypheny_prism_meta_responses_proto_goTypes,
		DependencyIndexes: file_org_polypheny_prism_meta_responses_proto_depIdxs,
		EnumInfos:         file_org_polypheny_prism_meta_responses_proto_enumTypes,
		MessageInfos:      file_org_polypheny_prism_meta_responses_proto_msgTypes,
	}.Build()
	File_org_polypheny_prism_meta_responses_proto = out.File
	file_org_polypheny_prism_meta_responses_proto_rawDesc = nil
	file_org_polypheny_prism_meta_responses_proto_goTypes = nil
	file_org_polypheny_prism_meta_responses_proto_depIdxs = nil
}
