//
//Messages related to describing the metadata of namespaces and their entities.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: polyprism/namespace_meta_requests.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The NamespaceRequest message is designed for querying specific details about a specific namespace.
type NamespaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the namespace for which details are being requested.
	NamespaceName string `protobuf:"bytes,1,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
}

func (x *NamespaceRequest) Reset() {
	*x = NamespaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polyprism_namespace_meta_requests_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceRequest) ProtoMessage() {}

func (x *NamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polyprism_namespace_meta_requests_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceRequest.ProtoReflect.Descriptor instead.
func (*NamespaceRequest) Descriptor() ([]byte, []int) {
	return file_polyprism_namespace_meta_requests_proto_rawDescGZIP(), []int{0}
}

func (x *NamespaceRequest) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

// The NamespacesRequest message allows querying for namespaces based on specific patterns in their names as well as their types.
type NamespacesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// An optional pattern that can be used to filter the returned namespaces based on their names.
	// For example, using a pattern like “user_*” might return all namespaces starting with “user_”.
	NamespacePattern *string `protobuf:"bytes,1,opt,name=namespace_pattern,json=namespacePattern,proto3,oneof" json:"namespace_pattern,omitempty"`
	// An optional type specifier that can be used to filter namespaces based on their type. This allows clients to request namespaces of a particular type.
	NamespaceType *string `protobuf:"bytes,2,opt,name=namespace_type,json=namespaceType,proto3,oneof" json:"namespace_type,omitempty"`
}

func (x *NamespacesRequest) Reset() {
	*x = NamespacesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polyprism_namespace_meta_requests_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespacesRequest) ProtoMessage() {}

func (x *NamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polyprism_namespace_meta_requests_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespacesRequest.ProtoReflect.Descriptor instead.
func (*NamespacesRequest) Descriptor() ([]byte, []int) {
	return file_polyprism_namespace_meta_requests_proto_rawDescGZIP(), []int{1}
}

func (x *NamespacesRequest) GetNamespacePattern() string {
	if x != nil && x.NamespacePattern != nil {
		return *x.NamespacePattern
	}
	return ""
}

func (x *NamespacesRequest) GetNamespaceType() string {
	if x != nil && x.NamespaceType != nil {
		return *x.NamespaceType
	}
	return ""
}

// The EntitiesRequest message is meant for querying details about entities within a specific namespace, possibly using a pattern to narrow down the results.
type EntitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the namespace within which entities are to be searched.
	NamespaceName string `protobuf:"bytes,1,opt,name=namespace_name,json=namespaceName,proto3" json:"namespace_name,omitempty"`
	// An optional pattern for filtering the returned entities. This can help in narrowing down the list of entities based on a naming pattern or other criteria.
	EntityPattern *string `protobuf:"bytes,2,opt,name=entity_pattern,json=entityPattern,proto3,oneof" json:"entity_pattern,omitempty"`
}

func (x *EntitiesRequest) Reset() {
	*x = EntitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polyprism_namespace_meta_requests_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitiesRequest) ProtoMessage() {}

func (x *EntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_polyprism_namespace_meta_requests_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitiesRequest.ProtoReflect.Descriptor instead.
func (*EntitiesRequest) Descriptor() ([]byte, []int) {
	return file_polyprism_namespace_meta_requests_proto_rawDescGZIP(), []int{2}
}

func (x *EntitiesRequest) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *EntitiesRequest) GetEntityPattern() string {
	if x != nil && x.EntityPattern != nil {
		return *x.EntityPattern
	}
	return ""
}

var File_polyprism_namespace_meta_requests_proto protoreflect.FileDescriptor

var file_polyprism_namespace_meta_requests_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x70, 0x6f, 0x6c, 0x79, 0x70,
	0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x22, 0x39, 0x0a, 0x10, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x9a,
	0x01, 0x0a, 0x11, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x11, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x10, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x61, 0x74, 0x74,
	0x65, 0x72, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x88,
	0x01, 0x01, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x77, 0x0a, 0x0f, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25,
	0x0a, 0x0e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x0e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f,
	0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0d, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x88, 0x01,
	0x01, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x70, 0x61, 0x74,
	0x74, 0x65, 0x72, 0x6e, 0x42, 0x38, 0x0a, 0x25, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79,
	0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x0d, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x50, 0x01, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_polyprism_namespace_meta_requests_proto_rawDescOnce sync.Once
	file_polyprism_namespace_meta_requests_proto_rawDescData = file_polyprism_namespace_meta_requests_proto_rawDesc
)

func file_polyprism_namespace_meta_requests_proto_rawDescGZIP() []byte {
	file_polyprism_namespace_meta_requests_proto_rawDescOnce.Do(func() {
		file_polyprism_namespace_meta_requests_proto_rawDescData = protoimpl.X.CompressGZIP(file_polyprism_namespace_meta_requests_proto_rawDescData)
	})
	return file_polyprism_namespace_meta_requests_proto_rawDescData
}

var file_polyprism_namespace_meta_requests_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_polyprism_namespace_meta_requests_proto_goTypes = []interface{}{
	(*NamespaceRequest)(nil),  // 0: polypheny.protointerface.NamespaceRequest
	(*NamespacesRequest)(nil), // 1: polypheny.protointerface.NamespacesRequest
	(*EntitiesRequest)(nil),   // 2: polypheny.protointerface.EntitiesRequest
}
var file_polyprism_namespace_meta_requests_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_polyprism_namespace_meta_requests_proto_init() }
func file_polyprism_namespace_meta_requests_proto_init() {
	if File_polyprism_namespace_meta_requests_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_polyprism_namespace_meta_requests_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polyprism_namespace_meta_requests_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NamespacesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polyprism_namespace_meta_requests_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_polyprism_namespace_meta_requests_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_polyprism_namespace_meta_requests_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_polyprism_namespace_meta_requests_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polyprism_namespace_meta_requests_proto_goTypes,
		DependencyIndexes: file_polyprism_namespace_meta_requests_proto_depIdxs,
		MessageInfos:      file_polyprism_namespace_meta_requests_proto_msgTypes,
	}.Build()
	File_polyprism_namespace_meta_requests_proto = out.File
	file_polyprism_namespace_meta_requests_proto_rawDesc = nil
	file_polyprism_namespace_meta_requests_proto_goTypes = nil
	file_polyprism_namespace_meta_requests_proto_depIdxs = nil
}
