//
//Messages related to statements in a query language and their results.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.24.3
// source: org/polypheny/prism/statement_responses.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response of the server on the request of a client to close the result set of a specific statement.
// This message has no fields. It merely serves as an acknowledgement.
type CloseResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseResultResponse) Reset() {
	*x = CloseResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResultResponse) ProtoMessage() {}

func (x *CloseResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResultResponse.ProtoReflect.Descriptor instead.
func (*CloseResultResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_statement_responses_proto_rawDescGZIP(), []int{0}
}

// Represents the response after executing a statement.
// This message contains the identifier of the executed statement and optionally, the result of the execution.
// The result can vary based on the type of statement executed, ranging from scalar values to complex data frames.
type StatementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique identifier of the executed statement.
	StatementId int32 `protobuf:"varint,1,opt,name=statement_id,json=statementId,proto3" json:"statement_id,omitempty"`
	// (Optional) The result of the executed statement.
	// This could be a scalar value or a data frame, depending on the type of statement executed.
	Result *StatementResult `protobuf:"bytes,2,opt,name=result,proto3,oneof" json:"result,omitempty"`
}

func (x *StatementResponse) Reset() {
	*x = StatementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatementResponse) ProtoMessage() {}

func (x *StatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatementResponse.ProtoReflect.Descriptor instead.
func (*StatementResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_statement_responses_proto_rawDescGZIP(), []int{1}
}

func (x *StatementResponse) GetStatementId() int32 {
	if x != nil {
		return x.StatementId
	}
	return 0
}

func (x *StatementResponse) GetResult() *StatementResult {
	if x != nil {
		return x.Result
	}
	return nil
}

// Encapsulates the result of an executed statement.
// This can include scalar values for simple queries or data frames for queries that return multiple rows or complex data.
type StatementResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A scalar result value, often used to represent the number of rows affected by an operation.
	Scalar int64 `protobuf:"varint,1,opt,name=scalar,proto3" json:"scalar,omitempty"`
	// (Optional) A frame of data, which could be a relational table, a graph, or a set of documents.
	Frame *Frame `protobuf:"bytes,2,opt,name=frame,proto3,oneof" json:"frame,omitempty"`
}

func (x *StatementResult) Reset() {
	*x = StatementResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatementResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatementResult) ProtoMessage() {}

func (x *StatementResult) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatementResult.ProtoReflect.Descriptor instead.
func (*StatementResult) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_statement_responses_proto_rawDescGZIP(), []int{2}
}

func (x *StatementResult) GetScalar() int64 {
	if x != nil {
		return x.Scalar
	}
	return 0
}

func (x *StatementResult) GetFrame() *Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

// Represents the response after executing a batch of statements.
// This includes the batch identifier and a list of scalar results for each statement in the batch,
// typically representing the number of rows affected by each operation.
type StatementBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique identifier of the executed batch.
	BatchId int32 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// List of scalar results for each statement in the batch.
	Scalars []int64 `protobuf:"varint,2,rep,packed,name=scalars,proto3" json:"scalars,omitempty"`
}

func (x *StatementBatchResponse) Reset() {
	*x = StatementBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatementBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatementBatchResponse) ProtoMessage() {}

func (x *StatementBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatementBatchResponse.ProtoReflect.Descriptor instead.
func (*StatementBatchResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_statement_responses_proto_rawDescGZIP(), []int{3}
}

func (x *StatementBatchResponse) GetBatchId() int32 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *StatementBatchResponse) GetScalars() []int64 {
	if x != nil {
		return x.Scalars
	}
	return nil
}

// Provides metadata about a prepared statement, including its parameters.
// This information is crucial for correctly binding parameters to the statement before execution.
type PreparedStatementSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The unique identifier of the prepared statement.
	StatementId int32 `protobuf:"varint,1,opt,name=statement_id,json=statementId,proto3" json:"statement_id,omitempty"`
	// Metadata about each parameter required by the statement, detailing type, name, and other characteristics.
	ParameterMetas []*ParameterMeta `protobuf:"bytes,2,rep,name=parameter_metas,json=parameterMetas,proto3" json:"parameter_metas,omitempty"`
}

func (x *PreparedStatementSignature) Reset() {
	*x = PreparedStatementSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreparedStatementSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedStatementSignature) ProtoMessage() {}

func (x *PreparedStatementSignature) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedStatementSignature.ProtoReflect.Descriptor instead.
func (*PreparedStatementSignature) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_statement_responses_proto_rawDescGZIP(), []int{4}
}

func (x *PreparedStatementSignature) GetStatementId() int32 {
	if x != nil {
		return x.StatementId
	}
	return 0
}

func (x *PreparedStatementSignature) GetParameterMetas() []*ParameterMeta {
	if x != nil {
		return x.ParameterMetas
	}
	return nil
}

// Provides metadata about a single parameter of a prepared statement.
// This includes details about the parameter's precision, scale, data type, and names.
type ParameterMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Precision of the parameter, typically used for numeric types.
	Precision int32 `protobuf:"varint,1,opt,name=precision,proto3" json:"precision,omitempty"`
	// Scale of the parameter, typically used for decimal types.
	Scale int32 `protobuf:"varint,2,opt,name=scale,proto3" json:"scale,omitempty"`
	// The data type of the parameter.
	TypeName string `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	// (Optional) The name of the placeholder specified for this value.
	ParameterName *string `protobuf:"bytes,4,opt,name=parameter_name,json=parameterName,proto3,oneof" json:"parameter_name,omitempty"`
	// The name of the parameter, if specified.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ParameterMeta) Reset() {
	*x = ParameterMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParameterMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterMeta) ProtoMessage() {}

func (x *ParameterMeta) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterMeta.ProtoReflect.Descriptor instead.
func (*ParameterMeta) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_statement_responses_proto_rawDescGZIP(), []int{5}
}

func (x *ParameterMeta) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *ParameterMeta) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *ParameterMeta) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ParameterMeta) GetParameterName() string {
	if x != nil && x.ParameterName != nil {
		return *x.ParameterName
	}
	return ""
}

func (x *ParameterMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Represents the response after closing a prepared statement.
// The message is currently empty, serving as a simple acknowledgment of the action.
// This message does not contain any fields. It simply serves as an acknowledgment.
type CloseStatementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CloseStatementResponse) Reset() {
	*x = CloseStatementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseStatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStatementResponse) ProtoMessage() {}

func (x *CloseStatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStatementResponse.ProtoReflect.Descriptor instead.
func (*CloseStatementResponse) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_statement_responses_proto_rawDescGZIP(), []int{6}
}

// Represents a frame of data that could be one of several types, offering flexibility in representing different types of data responses.
// This structure allows for a more generic interface that can handle various data structures.
type Frame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Indicates if this frame is the last in a series of frames, useful for paginated results.
	IsLast bool `protobuf:"varint,1,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	// The actual data frame. It could be a relational table (RelationalFrame), a graph (GraphFrame), or a document (DocumentFrame).
	//
	// Types that are assignable to Result:
	//
	//	*Frame_RelationalFrame
	//	*Frame_GraphFrame
	//	*Frame_DocumentFrame
	Result isFrame_Result `protobuf_oneof:"result"`
}

func (x *Frame) Reset() {
	*x = Frame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_org_polypheny_prism_statement_responses_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_org_polypheny_prism_statement_responses_proto_rawDescGZIP(), []int{7}
}

func (x *Frame) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (m *Frame) GetResult() isFrame_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *Frame) GetRelationalFrame() *RelationalFrame {
	if x, ok := x.GetResult().(*Frame_RelationalFrame); ok {
		return x.RelationalFrame
	}
	return nil
}

func (x *Frame) GetGraphFrame() *GraphFrame {
	if x, ok := x.GetResult().(*Frame_GraphFrame); ok {
		return x.GraphFrame
	}
	return nil
}

func (x *Frame) GetDocumentFrame() *DocumentFrame {
	if x, ok := x.GetResult().(*Frame_DocumentFrame); ok {
		return x.DocumentFrame
	}
	return nil
}

type isFrame_Result interface {
	isFrame_Result()
}

type Frame_RelationalFrame struct {
	RelationalFrame *RelationalFrame `protobuf:"bytes,2,opt,name=relational_frame,json=relationalFrame,proto3,oneof"`
}

type Frame_GraphFrame struct {
	GraphFrame *GraphFrame `protobuf:"bytes,3,opt,name=graph_frame,json=graphFrame,proto3,oneof"`
}

type Frame_DocumentFrame struct {
	DocumentFrame *DocumentFrame `protobuf:"bytes,4,opt,name=document_frame,json=documentFrame,proto3,oneof"`
}

func (*Frame_RelationalFrame) isFrame_Result() {}

func (*Frame_GraphFrame) isFrame_Result() {}

func (*Frame_DocumentFrame) isFrame_Result() {}

var File_org_polypheny_prism_statement_responses_proto protoreflect.FileDescriptor

var file_org_polypheny_prism_statement_responses_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x13, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70,
	0x72, 0x69, 0x73, 0x6d, 0x1a, 0x2a, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68,
	0x65, 0x6e, 0x79, 0x2f, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x25, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f,
	0x70, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x28, 0x6f, 0x72, 0x67, 0x2f, 0x70, 0x6f, 0x6c,
	0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2f, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2f, 0x64, 0x6f, 0x63,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x11, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x41, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e,
	0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x88, 0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x6a, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x12, 0x35, 0x0a, 0x05, 0x66, 0x72,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x72, 0x67, 0x2e,
	0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x16, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x07, 0x73, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x1a, 0x50,
	0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x4b, 0x0a, 0x0f,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79,
	0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x0e, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x22, 0xb3, 0x01, 0x0a, 0x0d, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x61,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x79, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x0e,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x11, 0x0a, 0x0f,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x18, 0x0a, 0x16, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8e, 0x02, 0x0a, 0x05, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x61, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x10,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c,
	0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0f,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12,
	0x42, 0x0a, 0x0b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70,
	0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73, 0x6d, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x70, 0x68, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x48,
	0x00, 0x52, 0x0d, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65,
	0x42, 0x08, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x2b, 0x0a, 0x13, 0x6f, 0x72,
	0x67, 0x2e, 0x70, 0x6f, 0x6c, 0x79, 0x70, 0x68, 0x65, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x69, 0x73,
	0x6d, 0x42, 0x12, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x73, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_polypheny_prism_statement_responses_proto_rawDescOnce sync.Once
	file_org_polypheny_prism_statement_responses_proto_rawDescData = file_org_polypheny_prism_statement_responses_proto_rawDesc
)

func file_org_polypheny_prism_statement_responses_proto_rawDescGZIP() []byte {
	file_org_polypheny_prism_statement_responses_proto_rawDescOnce.Do(func() {
		file_org_polypheny_prism_statement_responses_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_polypheny_prism_statement_responses_proto_rawDescData)
	})
	return file_org_polypheny_prism_statement_responses_proto_rawDescData
}

var file_org_polypheny_prism_statement_responses_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_org_polypheny_prism_statement_responses_proto_goTypes = []interface{}{
	(*CloseResultResponse)(nil),        // 0: org.polypheny.prism.CloseResultResponse
	(*StatementResponse)(nil),          // 1: org.polypheny.prism.StatementResponse
	(*StatementResult)(nil),            // 2: org.polypheny.prism.StatementResult
	(*StatementBatchResponse)(nil),     // 3: org.polypheny.prism.StatementBatchResponse
	(*PreparedStatementSignature)(nil), // 4: org.polypheny.prism.PreparedStatementSignature
	(*ParameterMeta)(nil),              // 5: org.polypheny.prism.ParameterMeta
	(*CloseStatementResponse)(nil),     // 6: org.polypheny.prism.CloseStatementResponse
	(*Frame)(nil),                      // 7: org.polypheny.prism.Frame
	(*RelationalFrame)(nil),            // 8: org.polypheny.prism.RelationalFrame
	(*GraphFrame)(nil),                 // 9: org.polypheny.prism.GraphFrame
	(*DocumentFrame)(nil),              // 10: org.polypheny.prism.DocumentFrame
}
var file_org_polypheny_prism_statement_responses_proto_depIdxs = []int32{
	2,  // 0: org.polypheny.prism.StatementResponse.result:type_name -> org.polypheny.prism.StatementResult
	7,  // 1: org.polypheny.prism.StatementResult.frame:type_name -> org.polypheny.prism.Frame
	5,  // 2: org.polypheny.prism.PreparedStatementSignature.parameter_metas:type_name -> org.polypheny.prism.ParameterMeta
	8,  // 3: org.polypheny.prism.Frame.relational_frame:type_name -> org.polypheny.prism.RelationalFrame
	9,  // 4: org.polypheny.prism.Frame.graph_frame:type_name -> org.polypheny.prism.GraphFrame
	10, // 5: org.polypheny.prism.Frame.document_frame:type_name -> org.polypheny.prism.DocumentFrame
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_org_polypheny_prism_statement_responses_proto_init() }
func file_org_polypheny_prism_statement_responses_proto_init() {
	if File_org_polypheny_prism_statement_responses_proto != nil {
		return
	}
	file_org_polypheny_prism_relational_frame_proto_init()
	file_org_polypheny_prism_graph_frame_proto_init()
	file_org_polypheny_prism_document_frame_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_org_polypheny_prism_statement_responses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_statement_responses_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_statement_responses_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatementResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_statement_responses_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatementBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_statement_responses_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreparedStatementSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_statement_responses_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParameterMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_statement_responses_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseStatementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_polypheny_prism_statement_responses_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_org_polypheny_prism_statement_responses_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_org_polypheny_prism_statement_responses_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_org_polypheny_prism_statement_responses_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_org_polypheny_prism_statement_responses_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Frame_RelationalFrame)(nil),
		(*Frame_GraphFrame)(nil),
		(*Frame_DocumentFrame)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_polypheny_prism_statement_responses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_org_polypheny_prism_statement_responses_proto_goTypes,
		DependencyIndexes: file_org_polypheny_prism_statement_responses_proto_depIdxs,
		MessageInfos:      file_org_polypheny_prism_statement_responses_proto_msgTypes,
	}.Build()
	File_org_polypheny_prism_statement_responses_proto = out.File
	file_org_polypheny_prism_statement_responses_proto_rawDesc = nil
	file_org_polypheny_prism_statement_responses_proto_goTypes = nil
	file_org_polypheny_prism_statement_responses_proto_depIdxs = nil
}
